### ISSUE TITLE
Update services

### ISSUE THREAD

**Issue by jeremydeclerck** [platformsh-templates/drupal10#101]
### What in this template can be improved or added as a feature?

Some of the services are using outdated or even use deprecated versions.

### What exactly should be updated?

- Drupal is compatible with php 8.2 as of Drupal 10. So it makes sense that a Drupal 10 template would use it by default.
- Redis 6.0 is deprecated.
- Mariadb 10.4 can be updated as well

### How important is this feature to you?

Not important. Minor inconvenience.

**Comment by rfay** [comment]
I think this was a mistake.

MariaDB 11.2 is not LTS, current LTS is MariaDB 10.11

If anything, this should be 10.11, but there wasn't a strong reason to change it anyway.

This broke ddev-platformsh plugin because we try not to support the many non-LTS versions of MariaDB

I'll open a PR to bring it to 10.11
